# Generated by Django 5.0.7 on 2024-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_class_created_at_class_level_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('graduate', 'Graduate')], default='Pending', max_length=20),
        ),
    ]
